spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Balsa27/SimplyEducation-Config-Files
          clone-on-start: true
          strict-host-key-checking: false
          force-pull: true
  profiles:
    active: dev
server:
  port: 9010
